--- #Docker YAML Installing Docker, the container runtime;
#Installing apt-transport-https, allowing you to add external HTTPS sources to the APT source list;
#Adding the apt key of the Kubernetes APT repository for key verification;
#Adding the Kubernetes APT repository to the remote server APT sources list;
#Installing Kubelet and Kubeadm
- hosts: demo
  user: ansibleusr1
  become: yes
  connection: ssh
  tasks:
      - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
 
      - name: set join command
      set_fact:
  	join_command: "{{ join_command_raw.stdout_lines[0] }}"
 
      - hosts: workers
      become: yes
      tasks:
 	- name: remove swap
 	shell: "swapoff -a"
 
	- name: join cluster	
 	shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
 	args:
  	 chdir: $HOME
  	 creates: node_joined.txt